language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "grace-shopper-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: isomers
  api_key:
    secure: H1an+wDeNg9ou6sn9QAClPxNisNnOMGcLYwII9gd1rBZiW+wHd707PcoCLeByuYIOEOYxZx19mm0klQ/IfF+MtqWHcBzS9y6Cd7J8zgyrWd/zgxJJvW0wpQxjP4pWO680c5V2YTPXfZMFc21sUxdhWkw2dXJoprWApjuVXeYWt8ZkTF1UD/sDIWgGIixdbuYOCgF+fBUqusKFNcoPEvpgWrPZlyNlrSSkjbN+FGY7fd6fBzF92DW2/tPsi/9Svmca7wy/LWuNe1AuB+BsVrwkfjJN0N07Jj7z+uHX4vTBNZ9ymSo90kxH2XbAOXA3thGcXNUPgvrc1FJ4guo0jBEceltoJ060Amk9suYMvmSdZ00BlmQst+W4UwW0w64D6U3ytilH+AaK5EUrleG2NYqi3xj7RIUvbAdLHX+nDxrF5LtbnMMmpSUiNGAS95VTZU1PNkmnSpUJcleO32+U5lrv4XmLUPb2XjDfLj0noNbSdXff+jfxsYz2xabJbkE65iCMhwbC7D9DE/bqz1iXnISXB039gA2MJvGyzBs6nEIpJ3ws2SnxqB1x6Pgb8d5JXa+H8samdG52rF4xJFXV5TWhtKvrYfj51kxIlaVqMj6gbFwPylPdsVYLUMYBikofTP1MxznTEy3RoiPCvCP2mP/9p7iFQ0RmaPjunj8opISK4A=
